version: '3'

services:
    vibe_web:
        build:
            context: docker/local/web
            dockerfile: Dockerfile
            args:
                - WWW_DATA_USER=${WWW_DATA_USER}
                - WWW_DATA_GROUP=${WWW_DATA_GROUP}
                - ENVIRONMENT=${APP_ENV}
        container_name: vibe_web
        ports:
            - '8080:80'
            - '8000:8000'
        volumes:
            - ./:/var/www/
            - ./docker/local/web/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/local/web/site.conf:/etc/nginx/sites-enabled/site.conf
        depends_on:
            - vibe_php

    vibe_php:
        image: inspection-inspection_php
        build:
            context: docker/local/php
            dockerfile: Dockerfile
            args:
                - WWW_DATA_USER=${WWW_DATA_USER}
                - WWW_DATA_GROUP=${WWW_DATA_GROUP}
                - ENVIRONMENT=${APP_ENV}
        container_name: vibe_php
        ports:
            - '6001:6001'
        expose:
            - "9000"
        environment:
            - WWW_DATA_USER=${WWW_DATA_USER}
        volumes:
            - ./:/var/www/
            - ./docker/local/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./docker/local/php/php_debug.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/local/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./docker/local/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/local/php/horizon/queue.conf:/etc/supervisor/conf.d/queue.conf
            - ./docker/local/php/horizon/schedule.conf:/etc/supervisor/conf.d/schedule.conf
            - ./docker/local/php/horizon/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/local/php/horizon/schedule.sh:/usr/local/bin/schedule.sh
            - ./data/logs:/var/log/supervisord
        depends_on:
            - vibe_mysql

    vibe_mysql:
        image: mysql:8.0
        container_name: vibe_mysql
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3309:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql

    vibe_mysql_test:
        image: mysql:8.0
        container_name: vibe_mysql_test
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}

    vibe_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        container_name: vibe_phpmyadmin
        depends_on:
            - vibe_mysql
        ports:
            - "8082:80"
        environment:
            - PMA_HOST=vibe_mysql
            - UPLOAD_LIMIT=300M
